import { Hono } from "hono";
import { zValidator } from "@hono/zod-validator";
import { prisma } from "../prisma";
import {
  DocumentGenerateSchema,
  HandoverProtocolDocumentGenerateSchema,
  PurchaseContractGenerateSchema,
} from "../types";
import { access } from "node:fs/promises";
import puppeteer, { type Browser } from "puppeteer";
import puppeteerCore from "puppeteer-core";
import chromium from "@sparticuz/chromium";
import { generateHandoverProtocolHtml } from "../lib/handoverProtocol";

const BROWSER_ARGS = ["--no-sandbox", "--disable-setuid-sandbox", "--disable-dev-shm-usage"];
const SYSTEM_BROWSER_PATHS = [
  "/usr/bin/chromium",
  "/usr/bin/chromium-browser",
  "/usr/bin/google-chrome",
  "/usr/bin/google-chrome-stable",
];

async function launchWithPuppeteer(): Promise<Browser> {
  return puppeteer.launch({
    args: BROWSER_ARGS,
    headless: true,
  });
}

async function canAccessPath(path: string): Promise<boolean> {
  try {
    await access(path);
    return true;
  } catch {
    return false;
  }
}

async function launchWithPuppeteerCore(executablePath: string, args: string[]): Promise<Browser> {
  return puppeteerCore.launch({
    executablePath,
    args,
    headless: true,
  });
}

// Launch browser compatible with both dev (puppeteer) and production (serverless chromium)
async function launchBrowser(): Promise<Browser> {
  const isProduction = process.env.NODE_ENV === "production" || process.env.VIBECODE_PRODUCTION === "true";
  if (!isProduction) {
    return launchWithPuppeteer();
  }

  const preferredPath = process.env.PUPPETEER_EXECUTABLE_PATH?.trim();
  if (preferredPath) {
    try {
      console.info(`[documents] using_browser_executable=${preferredPath}`);
      return await launchWithPuppeteerCore(preferredPath, BROWSER_ARGS);
    } catch (error) {
      console.warn("[documents] preferred_browser_launch_failed", error);
    }
  }

  for (const candidatePath of SYSTEM_BROWSER_PATHS) {
    if (!(await canAccessPath(candidatePath))) {
      continue;
    }

    try {
      console.info(`[documents] using_system_browser=${candidatePath}`);
      return await launchWithPuppeteerCore(candidatePath, BROWSER_ARGS);
    } catch (error) {
      console.warn(`[documents] system_browser_launch_failed path=${candidatePath}`, error);
    }
  }

  try {
    const executablePath = await chromium.executablePath();
    console.info(`[documents] using_sparticuz_browser=${executablePath}`);
    return await launchWithPuppeteerCore(executablePath, [...chromium.args, ...BROWSER_ARGS]);
  } catch (error) {
    console.warn("[documents] sparticuz_browser_launch_failed_fallback_to_puppeteer", error);
    return launchWithPuppeteer();
  }
}

async function htmlToPdf(html: string): Promise<Uint8Array> {
  const browser = await launchBrowser();
  try {
    const page = await browser.newPage();
    await page.setContent(html, { waitUntil: "networkidle0" });
    const pdfBuffer = await page.pdf({
      format: "A4",
      printBackground: true,
      margin: { top: "0", right: "0", bottom: "0", left: "0" },
    });
    console.info(`[documents] pdf_generated bytes=${pdfBuffer.length}`);
    return pdfBuffer;
  } catch (error) {
    console.error("[documents] pdf_generation_failed", error);
    throw error;
  } finally {
    await browser.close();
  }
}

const documentsRouter = new Hono();
const DEALER_NAME = "MainAuto Miltenberg Manuel Rui Fernandes";
const DEALER_ADDRESS = "Mainzer Str. 10 + 37";
const DEALER_CITY = "63897 Miltenberg";
const DEALER_WEB = "www.mainauto.eu";
const DEALER_EMAIL = "mainauto@gmail.com";
const DEALER_PHONE = "+49(0)9371-5054245";
const DEALER_TAX_ID = "DE196691148";
const DEALER_BANK = "Sparkasse Odenwaldkreis";
const DEALER_IBAN = "DE 59 5085 1952 0000 1147 77";
const DEALER_BIC = "HELADEF1ERB";
const LOGO_DATA_URI = `data:image/svg+xml;charset=UTF-8,${encodeURIComponent(`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 320 110"><rect width="320" height="110" fill="transparent"/><text x="8" y="70" font-family="Arial, Helvetica, sans-serif" font-size="72" font-style="italic" font-weight="700" fill="#0a3dff">M</text><text x="72" y="86" font-family="Georgia, Times New Roman, serif" font-size="96" font-style="italic" font-weight="700" fill="#e32119">A</text><text x="150" y="82" font-family="Arial, Helvetica, sans-serif" font-size="74" font-style="italic" font-weight="700" fill="#111111">uto</text></svg>`)}`;

interface DocumentParty {
  firstName: string;
  lastName: string;
  company: string | null;
  address: string | null;
  city: string | null;
  zip: string | null;
  country: string | null;
  email: string | null;
  phone: string | null;
  taxId: string | null;
}

function getDealerFooterHtml(): string {
  return `
    ${DEALER_NAME} &bull; ${DEALER_ADDRESS} &bull; ${DEALER_CITY}<br>
    E-Mail: ${DEALER_EMAIL} &bull; Tel. ${DEALER_PHONE} &bull; Web: ${DEALER_WEB}<br>
    ${DEALER_BANK} &bull; IBAN: ${DEALER_IBAN} &bull; BIC: ${DEALER_BIC}<br>
    USt-IdNr. ${DEALER_TAX_ID} &bull; Vertretungsberechtigt: Manuel Rui Fernandes
  `;
}

function getLogoImgHtml(className: string, logoSrc: string = LOGO_DATA_URI): string {
  return `<img src="${logoSrc}" alt="MainAuto" class="${className}" />`;
}

function getDealerHeaderHtml(logoSrc: string = LOGO_DATA_URI): string {
  const logoHtml = getLogoImgHtml("dealer-logo", logoSrc);

  return `
    <div class="dealer-header">
      <div class="dealer-brand">
        ${logoHtml}
        <div>
          <div class="dealer-name">${DEALER_NAME}</div>
          <div class="dealer-sub">${DEALER_ADDRESS} &bull; ${DEALER_CITY} &bull; Tel. ${DEALER_PHONE} &bull; Web: ${DEALER_WEB} &bull; Mail: ${DEALER_EMAIL} &bull; USt-IdNr. ${DEALER_TAX_ID}</div>
        </div>
      </div>
    </div>
  `;
}

function resolveDocumentLogoSrc(c: { req: { header: (name: string) => string | undefined } }): string {
  const origin = c.req.header("origin");
  const referer = c.req.header("referer");

  if (origin && /^https?:\/\//i.test(origin)) {
    return `${origin.replace(/\/$/, "")}/mainauto-logo.png`;
  }

  if (referer) {
    try {
      return `${new URL(referer).origin}/mainauto-logo.png`;
    } catch {
      return LOGO_DATA_URI;
    }
  }

  return LOGO_DATA_URI;
}

function resolveDocumentPublicAssetSrc(
  c: { req: { header: (name: string) => string | undefined } },
  filename: string
): string {
  const origin = c.req.header("origin");
  const referer = c.req.header("referer");

  if (origin && /^https?:\/\//i.test(origin)) {
    return `${origin.replace(/\/$/, "")}/${filename}`;
  }

  if (referer) {
    try {
      return `${new URL(referer).origin}/${filename}`;
    } catch {
      return `/${filename}`;
    }
  }

  return `/${filename}`;
}

function getPartyCityLine(party: Pick<DocumentParty, "zip" | "city" | "country">): string {
  const base = [party.zip, party.city].filter(Boolean).join(" ");
  if (party.country) {
    return base ? `${base} / ${party.country}` : party.country;
  }
  return base;
}

function normalizePartyFromCustomer(customer: {
  firstName: string;
  lastName: string;
  company: string | null;
  address: string | null;
  city: string | null;
  zip: string | null;
  country: string | null;
  email: string | null;
  phone: string | null;
  taxId: string | null;
}): DocumentParty {
  return {
    firstName: customer.firstName,
    lastName: customer.lastName,
    company: customer.company,
    address: customer.address,
    city: customer.city,
    zip: customer.zip,
    country: customer.country,
    email: customer.email,
    phone: customer.phone,
    taxId: customer.taxId,
  };
}

function normalizePartyFromSupplier(supplier: {
  name: string;
  supplierType: string | null;
  contactPerson: string | null;
  street: string | null;
  address: string | null;
  city: string | null;
  zip: string | null;
  country: string | null;
  email: string | null;
  phone: string | null;
}): DocumentParty {
  const rawName = (supplier.contactPerson ?? supplier.name).trim();
  const parts = rawName.split(/\s+/).filter(Boolean);
  const firstName = parts[0] ?? supplier.name;
  const lastName = parts.slice(1).join(" ") || "";

  return {
    firstName,
    lastName,
    company: supplier.supplierType === "gewerblich" ? supplier.name : null,
    address: supplier.street ?? supplier.address ?? null,
    city: supplier.city,
    zip: supplier.zip,
    country: supplier.country,
    email: supplier.email,
    phone: supplier.phone,
    taxId: null,
  };
}

async function resolveParty(
  source: "customer" | "supplier" | "manual",
  id?: string,
  manualParty?: Partial<DocumentParty>
): Promise<DocumentParty | null> {
  if (source === "manual") {
    if (!manualParty?.firstName || !manualParty?.lastName) {
      return null;
    }

    return {
      firstName: manualParty.firstName,
      lastName: manualParty.lastName,
      company: manualParty.company ?? null,
      address: manualParty.address ?? null,
      city: manualParty.city ?? null,
      zip: manualParty.zip ?? null,
      country: manualParty.country ?? null,
      email: manualParty.email ?? null,
      phone: manualParty.phone ?? null,
      taxId: manualParty.taxId ?? null,
    };
  }

  if (!id) {
    return null;
  }

  if (source === "customer") {
    const customer = await prisma.customer.findUnique({ where: { id } });
    return customer ? normalizePartyFromCustomer(customer) : null;
  }

  const supplier = await prisma.supplier.findUnique({ where: { id } });
  return supplier ? normalizePartyFromSupplier(supplier) : null;
}

function formatCurrency(amount: number): string {
  return new Intl.NumberFormat("de-DE", {
    style: "currency",
    currency: "EUR",
  }).format(amount);
}

function formatDate(date: Date): string {
  return new Intl.DateTimeFormat("de-DE", {
    day: "2-digit",
    month: "2-digit",
    year: "numeric",
  }).format(date);
}

/**
 * Tax calculation:
 * - Regular taxation (marginTaxed=false): gross = net * (1 + taxRate/100)
 * - Differenzbesteuerung (marginTaxed=true): sellingPrice IS the gross price
 *   (margin tax applies to the profit margin only, not shown to customer)
 */
function calculateGross(net: number, taxRate: number, marginTaxed: boolean): number {
  if (marginTaxed) {
    return net; // Price IS gross for Differenzbesteuerung
  }
  return net * (1 + taxRate / 100);
}

function calculateTaxAmount(net: number, taxRate: number, marginTaxed: boolean): number {
  if (marginTaxed) {
    return 0; // No separate tax shown for Differenzbesteuerung
  }
  return net * (taxRate / 100);
}

function baseStyles(): string {
  return `
    <style>
      * { margin: 0; padding: 0; box-sizing: border-box; }
      body { font-family: 'Segoe UI', Arial, Helvetica, sans-serif; font-size: 12pt; color: #222; line-height: 1.5; }
      .page { width: 210mm; min-height: 297mm; padding: 20mm; margin: 0 auto; background: white; }
      .header { display: flex; justify-content: space-between; align-items: flex-start; margin-bottom: 30px; border-bottom: 2px solid #333; padding-bottom: 15px; }
      .header-brand { display: flex; align-items: flex-start; gap: 10px; }
      .header-logo { width: 84px; height: auto; object-fit: contain; flex-shrink: 0; }
      .header h1 { font-size: 22pt; color: #333; }
      .header .date { font-size: 10pt; color: #666; }
      .section { margin-bottom: 20px; }
      .section h2 { font-size: 14pt; color: #333; border-bottom: 1px solid #ddd; padding-bottom: 5px; margin-bottom: 10px; }
      table { width: 100%; border-collapse: collapse; margin-bottom: 15px; }
      table th, table td { padding: 8px 12px; text-align: left; border-bottom: 1px solid #eee; }
      table th { background: #f5f5f5; font-weight: 600; width: 40%; }
      .total-row { font-weight: bold; font-size: 14pt; border-top: 2px solid #333; }
      .total-row td { padding-top: 12px; }
      .footer { margin-top: 40px; padding-top: 15px; border-top: 1px solid #ddd; font-size: 9pt; color: #888; text-align: center; }
      .margin-tax-note { font-size: 9pt; color: #666; font-style: italic; margin-top: 5px; }
      .signature-area { margin-top: 60px; display: flex; justify-content: space-between; }
      .signature-line { width: 45%; border-top: 1px solid #333; padding-top: 5px; font-size: 10pt; color: #666; }
      @media print { body { margin: 0; } .page { padding: 15mm; } }
    </style>
  `;
}

function generateOffer(
  vehicle: {
    brand: string;
    model: string;
    year: number | null;
    mileage: number;
    vin: string | null;
    hsn: string | null;
    tsn: string | null;
    registrationDocNumber: string | null;
    color: string | null;
    fuelType: string | null;
    transmission: string | null;
    power: string | null;
    sellingPrice: number;
    taxRate: number;
    marginTaxed: boolean;
    features: string | null;
  },
  customer?: {
    firstName: string;
    lastName: string;
    company: string | null;
    address: string | null;
    city: string | null;
    zip: string | null;
    email: string | null;
    phone: string | null;
  } | null
  ,
  logoSrc: string = LOGO_DATA_URI
): string {
  const gross = calculateGross(vehicle.sellingPrice, vehicle.taxRate, vehicle.marginTaxed);
  const tax = calculateTaxAmount(vehicle.sellingPrice, vehicle.taxRate, vehicle.marginTaxed);

  return `<!DOCTYPE html>
<html lang="de">
<head><meta charset="UTF-8"><title>Angebot</title>${baseStyles()}</head>
<body>
<div class="page">
  <div class="header">
    <div class="header-brand">
      ${getLogoImgHtml("header-logo", logoSrc)}
      <div>
        <h1>Angebot</h1>
        <p>Fahrzeugangebot</p>
      </div>
    </div>
    <div class="date">Datum: ${formatDate(new Date())}</div>
  </div>

  ${customer ? `
  <div class="section">
    <h2>Kunde</h2>
    <table>
      <tr><th>Name</th><td>${customer.company ? customer.company + " - " : ""}${customer.firstName} ${customer.lastName}</td></tr>
      ${customer.address ? `<tr><th>Adresse</th><td>${customer.address}${customer.zip ? ", " + customer.zip : ""}${customer.city ? " " + customer.city : ""}</td></tr>` : ""}
      ${customer.email ? `<tr><th>E-Mail</th><td>${customer.email}</td></tr>` : ""}
      ${customer.phone ? `<tr><th>Telefon</th><td>${customer.phone}</td></tr>` : ""}
    </table>
  </div>
  ` : ""}

  <div class="section">
    <h2>Fahrzeug</h2>
    <table>
      <tr><th>Fahrzeug</th><td>${vehicle.brand} ${vehicle.model}</td></tr>
      <tr><th>Baujahr</th><td>${vehicle.year}</td></tr>
      <tr><th>Kilometerstand</th><td>${vehicle.mileage.toLocaleString("de-DE")} km</td></tr>
      ${vehicle.vin ? `<tr><th>FIN</th><td>${vehicle.vin}</td></tr>` : ""}
      ${vehicle.color ? `<tr><th>Farbe</th><td>${vehicle.color}</td></tr>` : ""}
      ${vehicle.fuelType ? `<tr><th>Kraftstoff</th><td>${vehicle.fuelType}</td></tr>` : ""}
      ${vehicle.transmission ? `<tr><th>Getriebe</th><td>${vehicle.transmission}</td></tr>` : ""}
      ${vehicle.power ? `<tr><th>Leistung</th><td>${vehicle.power}</td></tr>` : ""}
    </table>
  </div>

  ${vehicle.features ? `
  <div class="section">
    <h2>Ausstattung</h2>
    <p>${(() => { try { return (JSON.parse(vehicle.features) as string[]).join(", "); } catch { return vehicle.features; } })()}</p>
  </div>
  ` : ""}

  <div class="section">
    <h2>Preis</h2>
    <table>
      ${vehicle.marginTaxed ? `
      <tr class="total-row"><th>Verkaufspreis</th><td>${formatCurrency(gross)}</td></tr>
      ` : `
      <tr><th>Netto</th><td>${formatCurrency(vehicle.sellingPrice)}</td></tr>
      <tr><th>MwSt. (${vehicle.taxRate}%)</th><td>${formatCurrency(tax)}</td></tr>
      <tr class="total-row"><th>Brutto</th><td>${formatCurrency(gross)}</td></tr>
      `}
    </table>
    ${vehicle.marginTaxed ? `<p class="margin-tax-note">Differenzbesteuerung gem. &sect; 25a UStG. Mehrwertsteuer wird nicht ausgewiesen.</p>` : ""}
  </div>

  <div class="footer">
    <p>Dieses Angebot ist freibleibend und unverbindlich. Irrt&uuml;mer und Zwischenverkauf vorbehalten.</p>
  </div>
</div>
</body>
</html>`;
}

function generatePriceTag(vehicle: {
  brand: string;
  model: string;
  year: number | null;
  mileage: number;
  color: string | null;
  fuelType: string | null;
  transmission: string | null;
  power: string | null;
  sellingPrice: number;
  taxRate: number;
  marginTaxed: boolean;
  features: string | null;
}, logoSrc: string = LOGO_DATA_URI): string {
  const gross = calculateGross(vehicle.sellingPrice, vehicle.taxRate, vehicle.marginTaxed);

  return `<!DOCTYPE html>
<html lang="de">
<head><meta charset="UTF-8"><title>Preisschild</title>
<style>
  * { margin: 0; padding: 0; box-sizing: border-box; }
  body { font-family: 'Segoe UI', Arial, Helvetica, sans-serif; }
  .price-tag { width: 210mm; padding: 25mm; margin: 0 auto; background: white; }
  .brand-strip { display: flex; align-items: center; justify-content: flex-start; margin-bottom: 18px; }
  .brand-logo { width: 92px; height: auto; object-fit: contain; }
  .vehicle-name { font-size: 28pt; font-weight: bold; color: #222; margin-bottom: 10px; }
  .vehicle-year { font-size: 16pt; color: #555; margin-bottom: 20px; }
  .details { display: grid; grid-template-columns: 1fr 1fr; gap: 8px; margin-bottom: 25px; }
  .detail-item { font-size: 12pt; color: #444; }
  .detail-label { font-weight: 600; }
  .price-section { background: #1a1a2e; color: white; padding: 20px 30px; border-radius: 8px; text-align: center; margin-top: 20px; }
  .price { font-size: 36pt; font-weight: bold; }
  .price-note { font-size: 10pt; margin-top: 5px; opacity: 0.8; }
  .features-section { margin-top: 20px; }
  .features-title { font-size: 14pt; font-weight: 600; margin-bottom: 8px; color: #333; }
  .features-list { font-size: 11pt; color: #555; line-height: 1.8; }
  @media print { body { margin: 0; } }
</style>
</head>
<body>
<div class="price-tag">
  <div class="brand-strip">${getLogoImgHtml("brand-logo", logoSrc)}</div>
  <div class="vehicle-name">${vehicle.brand} ${vehicle.model}</div>
  <div class="vehicle-year">Baujahr ${vehicle.year}</div>

  <div class="details">
    <div class="detail-item"><span class="detail-label">Kilometerstand:</span> ${vehicle.mileage.toLocaleString("de-DE")} km</div>
    ${vehicle.color ? `<div class="detail-item"><span class="detail-label">Farbe:</span> ${vehicle.color}</div>` : ""}
    ${vehicle.fuelType ? `<div class="detail-item"><span class="detail-label">Kraftstoff:</span> ${vehicle.fuelType}</div>` : ""}
    ${vehicle.transmission ? `<div class="detail-item"><span class="detail-label">Getriebe:</span> ${vehicle.transmission}</div>` : ""}
    ${vehicle.power ? `<div class="detail-item"><span class="detail-label">Leistung:</span> ${vehicle.power}</div>` : ""}
  </div>

  ${vehicle.features ? `
  <div class="features-section">
    <div class="features-title">Ausstattung</div>
    <div class="features-list">${(() => { try { return (JSON.parse(vehicle.features) as string[]).join(" &bull; "); } catch { return vehicle.features; } })()}</div>
  </div>
  ` : ""}

  <div class="price-section">
    <div class="price">${formatCurrency(gross)}</div>
    <div class="price-note">${vehicle.marginTaxed ? "Differenzbesteuert gem. &sect; 25a UStG" : `inkl. ${vehicle.taxRate}% MwSt.`}</div>
  </div>
</div>
</body>
</html>`;
}

function numberToGermanWords(n: number): string {
  if (n === 0) return "null";

  const ones = ["", "ein", "zwei", "drei", "vier", "fünf", "sechs", "sieben", "acht", "neun",
    "zehn", "elf", "zwölf", "dreizehn", "vierzehn", "fünfzehn", "sechzehn", "siebzehn", "achtzehn", "neunzehn"];
  const tens = ["", "", "zwanzig", "dreißig", "vierzig", "fünfzig", "sechzig", "siebzig", "achtzig", "neunzig"];

  function belowThousand(num: number): string {
    if (num === 0) return "";
    if (num < 20) return ones[num]!;
    const t = Math.floor(num / 10);
    const o = num % 10;
    if (o === 0) return tens[t]!;
    return ones[o] + "und" + tens[t];
  }

  function belowMillion(num: number): string {
    if (num === 0) return "";
    const h = Math.floor(num / 100);
    const rest = num % 100;
    let result = "";
    if (h > 0) result += ones[h] + "hundert";
    if (rest > 0) result += belowThousand(rest);
    return result;
  }

  let remaining = Math.round(n);
  let result = "";

  if (remaining >= 1000000) {
    const millions = Math.floor(remaining / 1000000);
    result += (millions === 1 ? "eine" : belowMillion(millions)) + " Million" + (millions === 1 ? "" : "en") + " ";
    remaining %= 1000000;
  }

  if (remaining >= 1000) {
    const thousands = Math.floor(remaining / 1000);
    result += (thousands === 1 ? "ein" : belowMillion(thousands)) + "tausend";
    remaining %= 1000;
    if (remaining > 0) result += " ";
  }

  if (remaining > 0) {
    result += belowMillion(remaining);
  }

  // Capitalize first letter and add "Euro"
  result = result.trim();
  result = result.charAt(0).toUpperCase() + result.slice(1);
  return result + " Euro";
}

function formatGermanPrice(amount: number): string {
  const rounded = Math.round(amount);
  if (amount === rounded) {
    return rounded.toLocaleString("de-DE") + " €";
  }
  return amount.toLocaleString("de-DE", { minimumFractionDigits: 2, maximumFractionDigits: 2 }) + " €";
}

function formatDateDE(date: Date | string | null | undefined): string {
  if (!date) return "";
  const d = typeof date === "string" ? new Date(date) : date;
  return new Intl.DateTimeFormat("de-DE", { day: "2-digit", month: "2-digit", year: "numeric" }).format(d);
}

function formatMonthYearDE(date: Date | string | null | undefined): string {
  if (!date) return "";
  const d = typeof date === "string" ? new Date(date) : date;
  const mm = String(d.getMonth() + 1).padStart(2, "0");
  const yyyy = d.getFullYear();
  return `${mm}-${yyyy}`;
}

function generateContract(
  vehicle: {
    brand: string;
    model: string;
    year: number | null;
    mileage: number;
    vin: string | null;
    hsn: string | null;
    tsn: string | null;
    registrationDocNumber: string | null;
    color: string | null;
    fuelType: string | null;
    transmission: string | null;
    power: string | null;
    sellingPrice: number;
    taxRate: number;
    marginTaxed: boolean;
    features: string | null;
    bodyType: string | null;
    displacement: number | null;
    powerKw: number | null;
    co2Emission: number | null;
    firstRegistration: Date | string | null;
    huDue: Date | string | null;
    previousOwners: number | null;
    hasDamage: boolean;
    vehicleNumber: string;
    notes: string | null;
  },
  customer: {
    firstName: string;
    lastName: string;
    company: string | null;
    address: string | null;
    city: string | null;
    zip: string | null;
    country: string | null;
    email: string | null;
    phone: string | null;
    phone2: string | null;
    taxId: string | null;
  }
  ,
  logoSrc: string = LOGO_DATA_URI
): string {
  const today = new Date();
  const todayFormatted = formatDateDE(today);

  // Parse features
  let featuresList: string[] = [];
  if (vehicle.features) {
    try {
      featuresList = JSON.parse(vehicle.features) as string[];
    } catch {
      featuresList = [vehicle.features];
    }
  }

  // Build power string
  let powerStr = "";
  if (vehicle.power) {
    powerStr = vehicle.power + " PS";
    if (vehicle.powerKw) powerStr += "  (" + vehicle.powerKw + " kW)";
  } else if (vehicle.powerKw) {
    powerStr = vehicle.powerKw + " kW";
  }

  // Build customer city/country line
  const customerCityLine = [customer.zip, customer.city].filter(Boolean).join(" ") +
    (customer.country ? " / " + customer.country : "");

  // Vehicle data rows: [label, value] - only include rows where value is truthy
  const vehicleRows: [string, string][] = [];

  if (vehicle.bodyType) vehicleRows.push(["Aufbau", vehicle.bodyType]);
  if (powerStr) vehicleRows.push(["Leistung", powerStr]);
  if (vehicle.vin) vehicleRows.push(["Fahrgestell-Nr.", vehicle.vin]);
  if (vehicle.hsn) vehicleRows.push(["HSN", vehicle.hsn]);
  if (vehicle.tsn) vehicleRows.push(["TSN", vehicle.tsn]);
  vehicleRows.push(["Fahrzeugbrief-Nr.", vehicle.registrationDocNumber ?? ""]);
  if (vehicle.color) vehicleRows.push(["Farbe", vehicle.color]);
  if (vehicle.transmission) vehicleRows.push(["Getriebe", vehicle.transmission]);
  if (vehicle.displacement) vehicleRows.push(["Hubraum", vehicle.displacement + " ccm"]);
  if (vehicle.fuelType) vehicleRows.push(["Kraftstoff", vehicle.fuelType]);

  // Anhängerkupplung: check features for tow hitch keywords
  const hasTowhitch = featuresList.some(f =>
    /anh.?ng|tow.?hitch|anh.ngevorrichtung/i.test(f)
  );
  vehicleRows.push(["Anh\u00e4ngerkupplung", hasTowhitch ? "ja" : "nein"]);

  if (vehicle.firstRegistration) vehicleRows.push(["Erstzulassung", formatDateDE(vehicle.firstRegistration)]);
  vehicleRows.push(["Km-Stand", vehicle.mileage.toLocaleString("de-DE") + " km"]);
  if (vehicle.huDue) {
    vehicleRows.push(["n\u00e4chste HU", formatMonthYearDE(vehicle.huDue)]);
    vehicleRows.push(["n\u00e4chste AU", formatMonthYearDE(vehicle.huDue)]);
  }
  if (vehicle.previousOwners !== null && vehicle.previousOwners !== undefined) {
    vehicleRows.push(["Anzahl Halter", String(vehicle.previousOwners)]);
  }
  vehicleRows.push(["Taxi-/Miet-/Fahrschule", "nein"]);
  vehicleRows.push(["Unfallfrei (lt. Vorbesitzer)", vehicle.hasDamage ? "nein" : "ja"]);
  vehicleRows.push(["Fahrzeug fahrbereit", "ja"]);
  vehicleRows.push(["Lieferdatum / verbindlich", todayFormatted + " / ja"]);

  const priceFormatted = formatGermanPrice(vehicle.sellingPrice);
  const priceInWords = numberToGermanWords(Math.round(vehicle.sellingPrice));

  const vehicleRowsHtml = vehicleRows
    .map(([label, value]) => `
        <tr>
          <td class="vd-label">${label}</td>
          <td class="vd-value">${value}</td>
        </tr>`)
    .join("");

  const ausstattungHtml = featuresList.length > 0
    ? `<div class="features-block">
        <p class="features-title">Ausstattung</p>
        <p class="features-text">${featuresList.join(" &bull; ")}</p>
      </div>`
    : "";

  const besondereInfoHtml = vehicle.notes
    ? `<div class="features-block">
        <p class="features-title">Besondere Informationen</p>
        <div class="features-text">${vehicle.notes}</div>
      </div>`
    : "";

  const co2Html = vehicle.co2Emission
    ? `<p class="co2-line">Komb. CO2-Emission (gewichtet): ${vehicle.co2Emission} g/km</p>`
    : "";

  const marginNoteHtml = vehicle.marginTaxed
    ? `<p class="margin-note">netto Export</p>`
    : "";

  return `<!DOCTYPE html>
<html lang="de">
<head>
<meta charset="UTF-8">
<title>Verbindliche Bestellung</title>
<style>
  * { margin: 0; padding: 0; box-sizing: border-box; }
  body { font-family: Arial, Helvetica, sans-serif; font-size: 9.5pt; color: #000; line-height: 1.45; background: #fff; }
  .page { width: 210mm; min-height: 297mm; padding: 14mm 16mm 14mm 16mm; margin: 0 auto; background: white; }

  /* Top system line - removed */

  /* Dealer header */
  .dealer-header { border-bottom: 2px solid #000; padding-bottom: 6px; margin-bottom: 10px; }
  .dealer-brand { display: flex; align-items: flex-start; gap: 12px; }
  .dealer-logo { width: 92px; height: auto; object-fit: contain; flex-shrink: 0; }
  .dealer-name { font-size: 13pt; font-weight: bold; color: #000; }
  .dealer-sub { font-size: 8.5pt; color: #333; margin-top: 2px; }

  /* Document title */
  .doc-title { font-size: 13pt; font-weight: bold; text-align: center; margin: 10px 0 4px; text-decoration: underline; }
  .doc-internalref { font-size: 8.5pt; text-align: right; margin-bottom: 8px; }

  /* Party blocks */
  .parties { display: flex; gap: 16px; margin-bottom: 10px; }
  .party-block { flex: 1; border: 1px solid #bbb; padding: 7px 9px; font-size: 8.5pt; }
  .party-block-title { font-weight: bold; font-size: 9pt; border-bottom: 1px solid #bbb; margin-bottom: 5px; padding-bottom: 3px; }

  /* Intro sentence */
  .intro-text { font-size: 8.5pt; margin-bottom: 8px; line-height: 1.5; }

  /* Vehicle heading */
  .vehicle-title { font-size: 12pt; font-weight: bold; margin-bottom: 6px; }

  /* Vehicle data table */
  .vd-table { width: 100%; border-collapse: collapse; margin-bottom: 8px; }
  .vd-table tr { border-bottom: 1px solid #e0e0e0; }
  .vd-label { width: 42%; font-weight: normal; color: #333; padding: 2.5px 4px 2.5px 0; font-size: 9pt; vertical-align: top; }
  .vd-value { width: 58%; padding: 2.5px 4px; font-size: 9pt; font-weight: bold; vertical-align: top; }

  /* Features */
  .features-block { margin: 8px 0; }
  .features-title { font-size: 8.5pt; font-weight: bold; margin-bottom: 3px; }
  .features-text { font-size: 8pt; color: #222; line-height: 1.5; }
  .features-text p { margin: 0 0 3px 0; }
  .features-text ul { margin: 0 0 3px 0; padding-left: 16px; }
  .features-text li { margin: 0; }
  .features-text strong { font-weight: bold; }

  /* Ausstattung section divider - removed */

  /* Price */
  .price-block { margin: 8px 0 4px; }
  .price-line { font-size: 13pt; font-weight: bold; margin-bottom: 2px; }
  .price-words { font-size: 9pt; margin-bottom: 2px; }
  .margin-note { font-size: 9pt; font-style: italic; color: #444; }
  .co2-line { font-size: 8.5pt; margin-top: 4px; color: #333; }

  /* Legal text */
  .legal-divider { border-top: 1px solid #bbb; margin: 10px 0 6px; }
  .legal-section-title { font-weight: bold; font-size: 8.5pt; margin-bottom: 5px; }
  .legal-text { font-size: 8pt; line-height: 1.55; color: #222; margin-bottom: 6px; }
  .notes-text { font-size: 8.5pt; color: #333; margin-bottom: 4px; font-style: italic; }

  /* Signature */
  .sig-row { display: flex; gap: 20px; margin-top: 22px; margin-bottom: 10px; }
  .sig-block { flex: 1; }
  .sig-label { font-size: 8pt; color: #555; margin-bottom: 18px; }
  .sig-line { border-top: 1px solid #000; padding-top: 3px; font-size: 8pt; color: #333; }
  .sig-city { font-size: 8.5pt; margin-top: 4px; }

  /* Footer */
  .doc-footer { border-top: 1.5px solid #000; margin-top: 18px; padding-top: 6px; font-size: 7.5pt; color: #333; text-align: center; line-height: 1.7; }

  @media print {
    body { margin: 0; }
    .page { padding: 12mm 14mm; }
  }
</style>
</head>
<body>
<div class="page">

  ${getDealerHeaderHtml(logoSrc)}

  <div class="doc-title">Verbindliche Bestellung eines gebrauchten Kraftfahrzeuges</div>
  <div class="doc-internalref">Interne Nr. ${vehicle.vehicleNumber}&nbsp;&nbsp;&nbsp;Export</div>

  <div class="parties">
    <div class="party-block">
      <div class="party-block-title">Verk&auml;ufer</div>
      <div>${DEALER_NAME}</div>
      <div>${DEALER_ADDRESS}</div>
      <div>${DEALER_CITY}</div>
      <div>Tel. ${DEALER_PHONE}, Web: ${DEALER_WEB}</div>
      <div>Mail: ${DEALER_EMAIL}, USt-IdNr. ${DEALER_TAX_ID}</div>
    </div>
    <div class="party-block">
      <div class="party-block-title">K&auml;ufer</div>
      ${customer.company ? `<div><strong>${customer.company}</strong></div>` : ""}
      <div>${customer.firstName} ${customer.lastName}</div>
      ${customer.address ? `<div>${customer.address}</div>` : ""}
      <div>${customerCityLine}</div>
      ${customer.phone ? `<div>Tel. ${customer.phone}${customer.phone2 ? ", " + customer.phone2 : ""}</div>` : ""}
      ${customer.email ? `<div>E-Mail: ${customer.email}</div>` : ""}
      ${customer.taxId ? `<div>USt-IdNr.: ${customer.taxId}</div>` : ""}
    </div>
  </div>

  <p class="intro-text">Der oben genannte K&auml;ufer kauft nach Ma&szlig;gabe und Kenntnisnahme der ausgeh&auml;ndigten Allgemeinen Gesch&auml;ftsbedingungen vom oben genannten Verk&auml;ufer folgendes Fahrzeug:</p>

  <div class="vehicle-title">${vehicle.brand} ${vehicle.model}</div>

  <table class="vd-table">
    <tbody>
      ${vehicleRowsHtml}
    </tbody>
  </table>

  ${ausstattungHtml}

  ${besondereInfoHtml}

  <div class="price-block">
    <div class="price-line">Kaufpreis: ${priceFormatted}</div>
    <div class="price-words">In Worten: ${priceInWords}</div>
    ${marginNoteHtml}
  </div>

  ${co2Html}

  <div class="legal-divider"></div>

  <div class="legal-section-title">Zahlungsweise + sonstige Vereinbarungen mit Vorrang auf die ausgeh&auml;ndigten Gesch&auml;ftsbedingungen:</div>

  <p class="legal-text">Der K&auml;ufer erkl&auml;rt ausdr&uuml;cklich, dass er Unternehmer im Sinne des &sect;2 UStG ist und das erworbene Fahrzeug in seiner Firma als Gesch&auml;ftsfahrzeug &uuml;berwiegend unternehmerisch nutzt oder aber gewerblich weiter ver&auml;u&szlig;ert. Der K&auml;ufer verzichtet ausdr&uuml;cklich auf eine Gew&auml;hrleistung durch den Verk&auml;ufer. Das Fahrzeug wird verkauft unter Ausschluss jeglicher Gew&auml;hrleistung. Ausgenommen hiervon sind Sch&auml;den wegen Verletzung von K&ouml;rper, Leben, Gesundheit sowie F&auml;lle vors&auml;tzlicher oder grob fahrl&auml;ssiger Sch&auml;digung des Vertragspartners.</p>

  <p class="legal-text">Der Verk&auml;ufer versichert die Richtigkeit der in diesem Vertrag niedergelegten Angaben &uuml;ber das Fahrzeug. Der Lieferzeitpunkt ist, wenn keine anderen Vereinbarungen getroffen wurden, das Datum des Ankaufs. Bei Minderj&auml;hrigen muss der Kaufvertrag durch den gesetzlichen Vertreter unterschrieben werden. Mit seiner Unterschrift best&auml;tigt der Verk&auml;ufer die Annahme der Bestellung.</p>

  <div class="sig-row">
    <div class="sig-block">
      <div class="sig-label">Ort, Datum</div>
      <div class="sig-line">Unterschrift K&auml;ufer</div>
    </div>
    <div class="sig-block">
      <div class="sig-label">&nbsp;</div>
      <div class="sig-line">Unterschrift Verk&auml;ufer</div>
    </div>
  </div>
  <div class="sig-city">Miltenberg, ${todayFormatted}</div>

  <div class="doc-footer">${getDealerFooterHtml()}</div>

</div>
</body>
</html>`;
}

function generatePurchaseContract(
  vehicle: {
    brand: string;
    model: string;
    mileage: number;
    vin: string | null;
    registrationDocNumber: string | null;
    color: string | null;
    fuelType: string | null;
    transmission: string | null;
    power: string | null;
    purchasePrice: number;
    taxRate: number;
    marginTaxed: boolean;
    features: string | null;
    bodyType: string | null;
    displacement: number | null;
    powerKw: number | null;
    firstRegistration: Date | string | null;
    huDue: Date | string | null;
    previousOwners: number | null;
    hasDamage: boolean;
    damageDescription: string | null;
    damageAmount: number | null;
    vehicleNumber: string;
    dealerPrice: number | null;
    notes: string | null;
  },
  seller: DocumentParty
  ,
  logoSrc: string = LOGO_DATA_URI
): string {
  const today = new Date();
  const todayFormatted = formatDateDE(today);
  const sellerCityLine = getPartyCityLine(seller);
  const contractPrice = vehicle.purchasePrice > 0 ? vehicle.purchasePrice : (vehicle.dealerPrice ?? 0);
  const priceFormatted = formatGermanPrice(contractPrice);
  const priceInWords = numberToGermanWords(Math.round(contractPrice));

  let featuresList: string[] = [];
  if (vehicle.features) {
    try {
      featuresList = JSON.parse(vehicle.features) as string[];
    } catch {
      featuresList = [vehicle.features];
    }
  }

  const hasTowhitch = featuresList.some((feature) => /anh.?ng|tow.?hitch|anh.ngevorrichtung/i.test(feature));
  const powerText = vehicle.powerKw
    ? `${vehicle.powerKw} kW`
    : vehicle.power
      ? `${vehicle.power} PS`
      : "";

  const leftRows = [
    ["Aufbau", vehicle.bodyType ?? ""],
    ["Leistung", powerText],
    ["Fahrgestell-Nr.", vehicle.vin ?? ""],
    ["Fahrzeugbrief-Nr.", vehicle.registrationDocNumber ?? ""],
    ["Farbe", vehicle.color ?? ""],
    ["Getriebe", vehicle.transmission ?? ""],
    ["Hubraum", vehicle.displacement ? `${vehicle.displacement} ccm` : ""],
    ["Kraftstoff", vehicle.fuelType ?? ""],
    ["Anhängerkupplung", hasTowhitch ? "ja" : "nein"],
  ].filter((row): row is [string, string] => Boolean(row[1]));

  const rightRows = [
    ["Erstzulassung", formatDateDE(vehicle.firstRegistration)],
    ["Km-Stand", `${vehicle.mileage.toLocaleString("de-DE")} km`],
    ["nächste HU", formatMonthYearDE(vehicle.huDue)],
    ["nächste AU", formatMonthYearDE(vehicle.huDue)],
    ["Anzahl Halter", vehicle.previousOwners != null ? String(vehicle.previousOwners) : ""],
    ["Taxi-/Miet-/Fahrschule", "nein"],
    ["Unfallfrei", vehicle.hasDamage ? "nein" : "ja"],
    ["Fahrzeug fahrbereit", "ja"],
    ["Bestellung verbindlich", "ja"],
    ["Übergabetermin", todayFormatted],
  ].filter((row): row is [string, string] => Boolean(row[1]));

  const rowHtml = (rows: [string, string][]) =>
    rows.map(([label, value]) => `
      <div class="data-row">
        <div class="data-label">${label}</div>
        <div class="data-value">${value}</div>
      </div>
    `).join("");

  const vehicleNoteParts = [vehicle.damageDescription, vehicle.notes?.replace(/<[^>]+>/g, " ").replace(/\s+/g, " ").trim()]
    .filter(Boolean);
  if (vehicle.damageAmount) {
    vehicleNoteParts.push(`Bekannte Aufbereitung/Reparatur ca. ${formatGermanPrice(vehicle.damageAmount)}`);
  }

  const priceTaxLabel = vehicle.marginTaxed
    ? "Differenzbesteuert"
    : `Regelbesteuert (${vehicle.taxRate}% MwSt.)`;

  return `<!DOCTYPE html>
<html lang="de">
<head>
<meta charset="UTF-8">
<title>Ankaufschein</title>
<style>
  * { margin: 0; padding: 0; box-sizing: border-box; }
  body { font-family: Arial, Helvetica, sans-serif; font-size: 9pt; color: #111; line-height: 1.4; background: #fff; }
  .page { width: 210mm; min-height: 297mm; padding: 14mm 16mm 14mm 16mm; margin: 0 auto; background: white; }
  .dealer-header { margin-bottom: 10px; }
  .dealer-brand { display: flex; align-items: flex-start; gap: 12px; }
  .dealer-logo { width: 92px; height: auto; object-fit: contain; flex-shrink: 0; }
  .dealer-name { font-size: 12pt; font-weight: bold; color: #111; }
  .dealer-sub { font-size: 8pt; color: #333; margin-top: 3px; line-height: 1.45; }
  .doc-head { display: flex; align-items: flex-start; justify-content: space-between; gap: 10px; background: #efefef; padding: 6px 8px; margin-bottom: 10px; }
  .doc-title { font-size: 18pt; font-weight: 700; line-height: 1; }
  .doc-subtitle { font-size: 10pt; font-weight: 700; margin-top: 2px; }
  .doc-internalref { font-size: 10pt; font-weight: 700; white-space: nowrap; }
  .party-section { display: grid; grid-template-columns: 94px 1fr; gap: 12px 18px; margin-bottom: 12px; font-size: 8.5pt; }
  .party-label { font-size: 14pt; font-weight: 700; }
  .party-content strong { display: block; margin-bottom: 2px; }
  .party-content div { margin-bottom: 1px; }
  .intro-text { font-size: 8.5pt; margin-bottom: 8px; }
  .vehicle-name { border: 1px solid #777; background: #e9e9e9; padding: 6px 8px; font-size: 18pt; font-weight: 700; margin-bottom: 6px; }
  .data-box { border: 1px solid #888; background: #f5f5f5; padding: 8px 8px 6px; }
  .data-grid { display: grid; grid-template-columns: 1fr 1fr; gap: 12px; }
  .data-row { display: grid; grid-template-columns: 110px 1fr; gap: 8px; font-size: 8.5pt; margin-bottom: 2px; }
  .data-label { color: #333; }
  .data-value { font-weight: 700; }
  .section-box { border: 1px solid #888; background: #f5f5f5; padding: 8px; margin-top: 4px; }
  .section-title { font-size: 10pt; font-weight: 700; margin-bottom: 4px; }
  .section-text { font-size: 8.5pt; line-height: 1.45; }
  .price-box { display: flex; align-items: flex-end; justify-content: space-between; gap: 12px; border: 1px solid #888; background: #efefef; padding: 8px; margin-top: 4px; }
  .price-main { font-size: 9pt; }
  .price-amount { font-size: 15pt; font-weight: 700; }
  .price-words { font-size: 7pt; color: #333; margin-top: 2px; text-transform: lowercase; }
  .price-tax { font-size: 9pt; font-weight: 700; text-align: right; }
  .legal-title { font-size: 9pt; font-weight: 700; margin: 14px 0 4px; }
  .legal-text { font-size: 7.6pt; line-height: 1.55; color: #222; margin-bottom: 6px; }
  .signature-row { display: grid; grid-template-columns: 1fr 1fr 1fr; gap: 8px; margin-top: 14px; align-items: end; }
  .signature-box { min-height: 34px; border: 1px solid #888; background: #efefef; padding: 4px 6px; font-size: 8pt; display: flex; align-items: flex-end; }
  .signature-box.center { justify-content: center; align-items: center; }
  .signature-logo { max-width: 72px; max-height: 24px; object-fit: contain; }
  .signature-labels { display: grid; grid-template-columns: 1fr 1fr 1fr; gap: 8px; font-size: 8pt; margin-top: 2px; }
  .doc-footer { margin-top: 12px; text-align: center; font-size: 7pt; line-height: 1.5; color: #333; }
  @media print {
    body { margin: 0; }
    .page { padding: 12mm 14mm; }
  }
</style>
</head>
<body>
<div class="page">
  ${getDealerHeaderHtml(logoSrc)}

  <div class="doc-head">
    <div>
      <div class="doc-title">Ankaufschein</div>
      <div class="doc-subtitle">Verbindlicher Ankauf eines gebrauchten Kraftfahrzeuges/Anh&auml;ngers</div>
    </div>
    <div class="doc-internalref">Interne Nr. ${vehicle.vehicleNumber}</div>
  </div>

  <div class="party-section">
    <div class="party-label">K&auml;ufer</div>
    <div class="party-content">
      <strong>${DEALER_NAME}</strong>
      <div>${DEALER_ADDRESS}, ${DEALER_CITY}</div>
      <div>Tel. ${DEALER_PHONE}, Web: ${DEALER_WEB}, Mail: ${DEALER_EMAIL}</div>
    </div>

    <div class="party-label">Verk&auml;ufer</div>
    <div class="party-content">
      ${seller.company ? `<strong>${seller.company}</strong>` : ""}
      <div>${seller.firstName} ${seller.lastName}</div>
      ${seller.address ? `<div>${seller.address}</div>` : ""}
      ${sellerCityLine ? `<div>${sellerCityLine}</div>` : ""}
      ${seller.phone ? `<div>Tel. ${seller.phone}</div>` : ""}
      ${seller.email ? `<div>E-Mail: ${seller.email}</div>` : ""}
      ${seller.taxId ? `<div>USt-IdNr.: ${seller.taxId}</div>` : ""}
    </div>
  </div>

  <p class="intro-text">Der oben genannte K&auml;ufer kauft vom oben genannten Verk&auml;ufer folgendes Fahrzeug:</p>

  <div class="vehicle-name">${vehicle.brand} ${vehicle.model}</div>

  <div class="data-box">
    <div class="data-grid">
      <div>${rowHtml(leftRows)}</div>
      <div>${rowHtml(rightRows)}</div>
    </div>
  </div>

  ${featuresList.length > 0 ? `
    <div class="section-box">
      <div class="section-title">Ausstattung</div>
      <div class="section-text">${featuresList.join(" &bull; ")}</div>
    </div>
  ` : ""}

  ${vehicleNoteParts.length > 0 ? `
    <div class="section-box">
      <div class="section-title">Hinweise</div>
      <div class="section-text">${vehicleNoteParts.join(" ")}</div>
    </div>
  ` : ""}

  <div class="price-box">
    <div class="price-main">
      <div class="price-amount">Ankaufspreis: ${priceFormatted}</div>
      <div class="price-words">In Worten: ${priceInWords.toLowerCase()}</div>
    </div>
    <div class="price-tax">${priceTaxLabel}</div>
  </div>

  <div class="legal-title">Zahlungsweise + sonstige Vereinbarungen mit Vorrang auf die ausgeh&auml;ndigten Gesch&auml;ftsbedingungen:</div>
  <p class="legal-text">Der Ankauf/tausch beruht auf dem zum Zeitpunkt des Ankaufes aktuellen Zustand des Fahrzeugs. Der Verk&auml;ufer erkl&auml;rt, das Fahrzeug in seinem rechtm&auml;&szlig;igen Eigentum zu haben und frei von Rechten Dritter zu &uuml;bergeben, soweit nichts anderes schriftlich vermerkt ist. F&uuml;r bekannte oder erkennbare M&auml;ngel, Vorsch&auml;den oder technische Besonderheiten des Fahrzeugs ist der Verk&auml;ufer zur wahrheitsgem&auml;&szlig;en Angabe verpflichtet.</p>
  <p class="legal-text">Mit der Unterschrift best&auml;tigt der Verk&auml;ufer, dass die Angaben zum Fahrzeug nach bestem Wissen richtig sind. Das Fahrzeug wird mit den ausgeh&auml;ndigten Unterlagen, Schl&uuml;sseln und dem vereinbarten Zubeh&ouml;r &uuml;bergeben. Falls eine Abl&ouml;sung oder Finanzierung besteht, ist dies vor &Uuml;bergabe offenzulegen.</p>
  <p class="legal-text">Die Zahlung erfolgt nach Vereinbarung per Barzahlung oder &Uuml;berweisung. Bis zur vollst&auml;ndigen &Uuml;bergabe aller zum Eigentums&uuml;bergang erforderlichen Unterlagen kann der K&auml;ufer die Auszahlung zur&uuml;ckhalten. Bei Minderj&auml;hrigen ist die Unterschrift des gesetzlichen Vertreters erforderlich.</p>

  <div class="signature-row">
    <div class="signature-box">Miltenberg, ${todayFormatted}</div>
    <div class="signature-box center">${getLogoImgHtml("signature-logo", logoSrc)}</div>
    <div class="signature-box"></div>
  </div>
  <div class="signature-labels">
    <div>Ort, Datum</div>
    <div>Unterschrift K&auml;ufer</div>
    <div>Unterschrift Verk&auml;ufer</div>
  </div>

  <div class="doc-footer">${getDealerFooterHtml()}</div>
</div>
</body>
</html>`;
}

// POST /api/documents/generate - generate document HTML
documentsRouter.post(
  "/generate",
  zValidator("json", DocumentGenerateSchema),
  async (c) => {
    const { type, vehicleId, customerId } = c.req.valid("json");
    const logoSrc = resolveDocumentLogoSrc(c);

    const vehicle = await prisma.vehicle.findUnique({
      where: { id: vehicleId },
    });

    if (!vehicle) {
      return c.json({ error: { message: "Vehicle not found", code: "NOT_FOUND" } }, 404);
    }

    let customer = null;
    if (customerId) {
      customer = await prisma.customer.findUnique({
        where: { id: customerId },
      });
      if (!customer) {
        return c.json({ error: { message: "Customer not found", code: "NOT_FOUND" } }, 404);
      }
    }

    let html: string;

    switch (type) {
      case "offer":
        html = generateOffer(vehicle, customer, logoSrc);
        break;
      case "price-tag":
        html = generatePriceTag(vehicle, logoSrc);
        break;
      case "contract":
        if (!customer) {
          return c.json(
            { error: { message: "Customer is required for contract generation", code: "BAD_REQUEST" } },
            400
          );
        }
        html = generateContract(vehicle, customer, logoSrc);
        break;
      default:
        return c.json({ error: { message: "Invalid document type", code: "BAD_REQUEST" } }, 400);
    }

    return c.json({ data: { html, type, vehicleNumber: vehicle.vehicleNumber } });
  }
);

// POST /api/documents/generate-pdf - generate contract as PDF binary
documentsRouter.post(
  "/generate-pdf",
  zValidator("json", DocumentGenerateSchema),
  async (c) => {
    const { type, vehicleId, customerId } = c.req.valid("json");
    const logoSrc = resolveDocumentLogoSrc(c);

    if (type !== "contract") {
      return c.json({ error: { message: "PDF generation only supported for contract", code: "BAD_REQUEST" } }, 400);
    }

    const vehicle = await prisma.vehicle.findUnique({ where: { id: vehicleId } });
    if (!vehicle) {
      return c.json({ error: { message: "Vehicle not found", code: "NOT_FOUND" } }, 404);
    }

    if (!customerId) {
      return c.json({ error: { message: "Customer is required for contract", code: "BAD_REQUEST" } }, 400);
    }

    const customer = await prisma.customer.findUnique({ where: { id: customerId } });
    if (!customer) {
      return c.json({ error: { message: "Customer not found", code: "NOT_FOUND" } }, 404);
    }

    const html = generateContract(vehicle, customer, logoSrc);

    try {
      const pdfBuffer = await htmlToPdf(html);
      c.header("Content-Type", "application/pdf");
      c.header("Content-Disposition", `attachment; filename="Kaufvertrag_${vehicle.vehicleNumber}.pdf"`);
      c.header("X-Vehicle-Number", vehicle.vehicleNumber);
      return c.body(pdfBuffer as unknown as ReadableStream);
    } catch (error) {
      console.error("[documents] contract_pdf_generation_failed", { vehicleId, customerId, error });
      return c.json({ error: { message: "Fehler beim Erstellen des Dokuments", code: "PDF_GENERATION_FAILED" } }, 500);
    }
  }
);

documentsRouter.post(
  "/generate-purchase-html",
  zValidator("json", PurchaseContractGenerateSchema),
  async (c) => {
    const { vehicleId, sellerSource, sellerId, manualSeller } = c.req.valid("json");
    const logoSrc = resolveDocumentLogoSrc(c);

    const vehicle = await prisma.vehicle.findUnique({ where: { id: vehicleId } });
    if (!vehicle) {
      return c.json({ error: { message: "Vehicle not found", code: "NOT_FOUND" } }, 404);
    }

    const seller = await resolveParty(sellerSource, sellerId, manualSeller);
    if (!seller) {
      return c.json({ error: { message: "Seller not found", code: "NOT_FOUND" } }, 404);
    }

    const html = generatePurchaseContract(vehicle, seller, logoSrc);
    return c.json({ data: { html, vehicleNumber: vehicle.vehicleNumber } });
  }
);

documentsRouter.post(
  "/generate-purchase-pdf",
  zValidator("json", PurchaseContractGenerateSchema),
  async (c) => {
    const { vehicleId, sellerSource, sellerId, manualSeller } = c.req.valid("json");
    const logoSrc = resolveDocumentLogoSrc(c);

    const vehicle = await prisma.vehicle.findUnique({ where: { id: vehicleId } });
    if (!vehicle) {
      return c.json({ error: { message: "Vehicle not found", code: "NOT_FOUND" } }, 404);
    }

    const seller = await resolveParty(sellerSource, sellerId, manualSeller);
    if (!seller) {
      return c.json({ error: { message: "Seller not found", code: "NOT_FOUND" } }, 404);
    }

    const html = generatePurchaseContract(vehicle, seller, logoSrc);

    try {
      const pdfBuffer = await htmlToPdf(html);
      c.header("Content-Type", "application/pdf");
      c.header("Content-Disposition", `attachment; filename="Ankaufvertrag_${vehicle.vehicleNumber}.pdf"`);
      c.header("X-Vehicle-Number", vehicle.vehicleNumber);
      return c.body(pdfBuffer as unknown as ReadableStream);
    } catch (error) {
      console.error("[documents] purchase_contract_pdf_generation_failed", {
        vehicleId,
        sellerSource,
        sellerId,
        error,
      });
      return c.json({ error: { message: "Fehler beim Erstellen des Dokuments", code: "PDF_GENERATION_FAILED" } }, 500);
    }
  }
);

// ─── Gelangensbestätigung ─────────────────────────────────────────────────────

function generateGelangensbestaetigung(
  vehicle: {
    brand: string;
    model: string;
    mileage: number;
    vin: string | null;
    power: string | null;
    powerKw: number | null;
    vehicleNumber: string;
  },
  customer: {
    firstName: string;
    lastName: string;
    company: string | null;
    address: string | null;
    city: string | null;
    zip: string | null;
    country: string | null;
    phone: string | null;
    taxId: string | null;
    idDocumentType: string | null;
    idDocumentNumber: string | null;
    idDocumentValidUntil: Date | string | null;
  },
  extra: {
    dateOfReceipt: string;
    passportType: string;
    passportNumber: string;
    passportValidUntil: string;
  }
  ,
  logoSrc: string = LOGO_DATA_URI
): string {
  // Build customer name line
  const customerName = customer.company
    ? customer.company
    : `${customer.firstName} ${customer.lastName}`;

  // Build customer address lines
  const addrLine1 = customer.address ?? "";
  const addrLine2 = [customer.zip, customer.city].filter(Boolean).join(" ") +
    (customer.country ? ` / ${customer.country}` : "");

  // Customer header line (one-liner for top)
  const customerOneLiner = [
    customerName,
    customer.address,
    addrLine2,
  ].filter(Boolean).join(" \u2022  ");

  // Power string
  let powerStr = "";
  if (vehicle.powerKw) {
    powerStr = `${vehicle.powerKw} kW`;
    if (vehicle.power) powerStr += ` / ${vehicle.power} PS`;
  } else if (vehicle.power) {
    powerStr = `${vehicle.power} PS`;
  }

  const passportTypeValue = extra.passportType || customer.idDocumentType || "";
  const passportNumberValue = extra.passportNumber || customer.idDocumentNumber || "";
  const passportValidUntilRaw =
    extra.passportValidUntil ||
    (customer.idDocumentValidUntil ? formatDateDE(customer.idDocumentValidUntil) : "");
  const passportValidUntilValue = /^\d{4}-\d{2}-\d{2}$/.test(passportValidUntilRaw)
    ? formatDateDE(passportValidUntilRaw)
    : passportValidUntilRaw;
  const dateOfReceiptValue = /^\d{4}-\d{2}-\d{2}$/.test(extra.dateOfReceipt)
    ? formatDateDE(extra.dateOfReceipt)
    : extra.dateOfReceipt;

  return `<!DOCTYPE html>
<html lang="de">
<head>
<meta charset="UTF-8">
<title>Gelangensbestätigung</title>
<style>
  * { margin: 0; padding: 0; box-sizing: border-box; }
  body { font-family: Arial, Helvetica, sans-serif; font-size: 9.5pt; color: #000; line-height: 1.5; background: #fff; }
  .page { width: 210mm; min-height: 297mm; padding: 14mm 16mm 14mm 16mm; margin: 0 auto; background: white; }

  .doc-header { display: flex; align-items: flex-start; justify-content: space-between; gap: 14px; margin-bottom: 8px; }
  .doc-logo { width: 88px; height: auto; object-fit: contain; flex-shrink: 0; }
  .doc-head-copy { flex: 1; }
  .top-note { font-size: 8pt; color: #555; text-align: center; margin-bottom: 10px; font-style: italic; border-bottom: 1px solid #ddd; padding-bottom: 8px; }

  .doc-title-en { font-size: 15pt; font-weight: bold; text-align: center; margin-bottom: 2px; }
  .doc-title-de { font-size: 11pt; font-weight: bold; text-align: center; margin-bottom: 2px; }
  .doc-subtitle { font-size: 9pt; text-align: center; color: #444; margin-bottom: 12px; }

  .customer-header { font-size: 8.5pt; text-align: center; margin-bottom: 14px; color: #222; }

  .two-col { display: flex; gap: 20px; margin-bottom: 14px; }
  .seller-block { flex: 1; font-size: 8.5pt; line-height: 1.7; }
  .seller-block .name { font-weight: bold; font-size: 10pt; }

  .cert-text { font-size: 8.5pt; margin-bottom: 14px; line-height: 1.6; }

  .section-title { font-weight: bold; font-size: 9.5pt; margin-bottom: 6px; border-bottom: 1.5px solid #000; padding-bottom: 3px; }

  .vehicle-block { margin-bottom: 14px; }
  .vehicle-line { font-size: 9pt; margin-bottom: 2px; }
  .vehicle-main { font-size: 11pt; font-weight: bold; margin-bottom: 3px; }

  .delivery-block { margin-bottom: 16px; font-size: 9pt; line-height: 1.7; }

  .confirm-text { font-size: 8.5pt; margin-bottom: 20px; line-height: 1.6; border-top: 1px solid #ccc; padding-top: 10px; }

  .sig-grid { display: grid; grid-template-columns: 1fr 1fr 1fr 1fr; gap: 12px; margin-top: 16px; }
  .sig-item { }
  .sig-label { font-size: 7.5pt; color: #555; margin-bottom: 4px; line-height: 1.3; }
  .sig-value { border-bottom: 1px solid #000; min-height: 22px; padding-bottom: 2px; font-size: 9pt; }
  .sig-full { margin-top: 20px; }
  .sig-full-line { border-bottom: 1px solid #000; min-height: 22px; }
  .sig-full-label { font-size: 7.5pt; color: #555; margin-top: 4px; }

  .doc-footer { border-top: 1.5px solid #000; margin-top: 24px; padding-top: 6px; font-size: 7.5pt; color: #333; text-align: center; line-height: 1.7; }

  @media print {
    body { margin: 0; }
    .page { padding: 12mm 14mm; }
  }
</style>
</head>
<body>
<div class="page">

  <div class="doc-header">
    ${getLogoImgHtml("doc-logo", logoSrc)}
    <div class="doc-head-copy">
      <div class="top-note">After signature, please send this document back to seller. &nbsp;|&nbsp; Bitte senden Sie dieses Dokument unterschrieben zur&uuml;ck an den Verk&auml;ufer.</div>
      <div class="doc-title-en">Delivery receipt</div>
      <div class="doc-title-de">Lieferschein / Gelangensbest&auml;tigung</div>
      <div class="doc-subtitle">(Export to EU Member State) &nbsp;/&nbsp; (Export in EU-Mitgliedsstaat)</div>
    </div>
  </div>

  <div class="customer-header">${customerOneLiner}</div>

  <div class="two-col">
    <div class="seller-block">
      <div class="name">MainAuto Miltenberg Manuel Rui Fernandes</div>
      <div>Mainzer Str. 10 + 37</div>
      <div>63897 Miltenberg</div>
      <div>GERMANY</div>
      <div>Phone / Tel. +49(0)9371-5054245</div>
      <div>Fax</div>
      <div>Tax-No. / USt-IdNr. DE196691148</div>
    </div>
  </div>

  <p class="cert-text">
    Certificate of the proper proof of delivery of the following vehicle to the designated delivery address.<br>
    <em>Gelangensbest&auml;tigung &uuml;ber die Verbringung des nachfolgend genannten Fahrzeugs an die unten angegebene Lieferadresse.</em>
  </p>

  <div class="vehicle-block">
    <div class="section-title">Vehicle / Fahrzeug</div>
    <div class="vehicle-line">Quantity / Anzahl: 1</div>
    <div class="vehicle-main">${vehicle.brand} ${vehicle.model}</div>
    ${powerStr ? `<div class="vehicle-line">${powerStr} / Mileage: ${vehicle.mileage.toLocaleString("de-DE")} km</div>` : `<div class="vehicle-line">Mileage: ${vehicle.mileage.toLocaleString("de-DE")} km</div>`}
    ${vehicle.vin ? `<div class="vehicle-line">Vehicle Ident-No. / Fahrgestellnummer: <strong>${vehicle.vin}</strong></div>` : ""}
  </div>

  <div class="delivery-block">
    <div class="section-title">Delivery address / Lieferadresse</div>
    <div><strong>${customerName}</strong></div>
    ${addrLine1 ? `<div>${addrLine1}</div>` : ""}
    ${addrLine2 ? `<div>${addrLine2}</div>` : ""}
    ${customer.phone ? `<div>Phone / Tel. ${customer.phone}</div>` : ""}
    ${customer.taxId ? `<div>Tax-No. / USt-IdNr. ${customer.taxId}</div>` : ""}
  </div>

  <p class="confirm-text">
    I hereby certify the proper proof of delivery of the above described vehicle to the designated delivery address. /
    <em>Ich best&auml;tige hiermit die ordnungsgem&auml;&szlig;e Verbringung des oben n&auml;her bezeichneten Fahrzeugs an die hier genannte Lieferadresse.</em>
  </p>

  <div class="sig-grid">
    <div class="sig-item">
      <div class="sig-label">Passport type / Art des Ausweisdokuments</div>
      <div class="sig-value">${passportTypeValue}</div>
    </div>
    <div class="sig-item">
      <div class="sig-label">Passport number / Ausweisnummer</div>
      <div class="sig-value">${passportNumberValue}</div>
    </div>
    <div class="sig-item">
      <div class="sig-label">Valid until / Gültig bis</div>
      <div class="sig-value">${passportValidUntilValue}</div>
    </div>
    <div class="sig-item">
      <div class="sig-label">Date of receipt / Datum des Empfangs</div>
      <div class="sig-value">${dateOfReceiptValue}</div>
    </div>
  </div>

  <div class="sig-full">
    <div class="sig-full-line"></div>
    <div class="sig-full-label">Signature, stamp of vehicle recipient / Unterschrift des Fahrzeugempf&auml;ngers</div>
  </div>

  <div class="doc-footer">
    MainAuto Miltenberg Manuel Rui Fernandes &bull; Mainzer Str. 10 + 37 &bull; 63897 Miltenberg<br>
    E-Mail: mainauto@gmail.com &bull; Tel. +49(0)9371-5054245<br>
    Sparkasse Odenwaldkreis &bull; IBAN: DE 59 5085 1952 0000 1147 77 &bull; BIC: HELADEF1ERB<br>
    USt-IdNr. DE196691148 &bull; Vertretungsberechtigt: Manuel Rui Fernandes
  </div>

</div>
</body>
</html>`;
}

// POST /api/documents/generate-gelangensbestaetigung
documentsRouter.post(
  "/generate-gelangensbestaetigung",
  async (c) => {
    const body = await c.req.json();
    const logoSrc = resolveDocumentLogoSrc(c);
    const { vehicleId, customerId, dateOfReceipt, passportType, passportNumber, passportValidUntil } = body;

    if (!vehicleId || !customerId) {
      return c.json({ error: { message: "vehicleId and customerId required", code: "BAD_REQUEST" } }, 400);
    }

    const vehicle = await prisma.vehicle.findUnique({ where: { id: vehicleId } });
    if (!vehicle) return c.json({ error: { message: "Vehicle not found", code: "NOT_FOUND" } }, 404);

    const customer = await prisma.customer.findUnique({ where: { id: customerId } });
    if (!customer) return c.json({ error: { message: "Customer not found", code: "NOT_FOUND" } }, 404);

    const html = generateGelangensbestaetigung(vehicle, customer, {
      dateOfReceipt: dateOfReceipt ?? "",
      passportType: passportType ?? customer.idDocumentType ?? "",
      passportNumber: passportNumber ?? customer.idDocumentNumber ?? "",
      passportValidUntil:
        passportValidUntil ??
        (customer.idDocumentValidUntil ? formatDateDE(customer.idDocumentValidUntil) : ""),
    }, logoSrc);

    try {
      const pdfBuffer = await htmlToPdf(html);
      c.header("Content-Type", "application/pdf");
      c.header("Content-Disposition", `attachment; filename="Gelangensbestaetigung_${vehicle.vehicleNumber}.pdf"`);
      return c.body(pdfBuffer as unknown as ReadableStream);
    } catch (error) {
      console.error("[documents] gelangensbestaetigung_pdf_generation_failed", { vehicleId, customerId, error });
      return c.json({ error: { message: "Fehler beim Erstellen des Dokuments", code: "PDF_GENERATION_FAILED" } }, 500);
    }
  }
);

// POST /api/documents/generate-gelangensbestaetigung-html (for saving)
documentsRouter.post(
  "/generate-gelangensbestaetigung-html",
  async (c) => {
    const body = await c.req.json();
    const logoSrc = resolveDocumentLogoSrc(c);
    const { vehicleId, customerId, dateOfReceipt, passportType, passportNumber, passportValidUntil } = body;
    const vehicle = await prisma.vehicle.findUnique({ where: { id: vehicleId } });
    if (!vehicle) return c.json({ error: { message: "Vehicle not found", code: "NOT_FOUND" } }, 404);
    const customer = await prisma.customer.findUnique({ where: { id: customerId } });
    if (!customer) return c.json({ error: { message: "Customer not found", code: "NOT_FOUND" } }, 404);
    const html = generateGelangensbestaetigung(vehicle, customer, {
      dateOfReceipt: dateOfReceipt ?? "",
      passportType: passportType ?? customer.idDocumentType ?? "",
      passportNumber: passportNumber ?? customer.idDocumentNumber ?? "",
      passportValidUntil:
        passportValidUntil ??
        (customer.idDocumentValidUntil ? formatDateDE(customer.idDocumentValidUntil) : ""),
    }, logoSrc);
    return c.json({ data: { html } });
  }
);

// ─── Vermittlungsvertrag ──────────────────────────────────────────────────────

function generateVermittlungsvertrag(
  vehicle: {
    brand: string;
    model: string;
    year: number | null;
    mileage: number;
    vin: string | null;
    hsn: string | null;
    tsn: string | null;
    registrationDocNumber: string | null;
    color: string | null;
    fuelType: string | null;
    transmission: string | null;
    power: string | null;
    sellingPrice: number;
    taxRate: number;
    marginTaxed: boolean;
    features: string | null;
    bodyType: string | null;
    displacement: number | null;
    powerKw: number | null;
    co2Emission: number | null;
    firstRegistration: Date | string | null;
    huDue: Date | string | null;
    previousOwners: number | null;
    hasDamage: boolean;
    vehicleNumber: string;
    notes: string | null;
  },
  buyer: {
    firstName: string;
    lastName: string;
    company: string | null;
    address: string | null;
    city: string | null;
    zip: string | null;
    country: string | null;
    email: string | null;
    phone: string | null;
    taxId: string | null;
  },
  seller: {
    firstName: string;
    lastName: string;
    company: string | null;
    address: string | null;
    city: string | null;
    zip: string | null;
    country: string | null;
    email: string | null;
    phone: string | null;
    taxId: string | null;
  }
  ,
  logoSrc: string = LOGO_DATA_URI
): string {
  const today = new Date();
  const todayFormatted = formatDateDE(today);

  // Parse features
  let featuresList: string[] = [];
  if (vehicle.features) {
    try {
      featuresList = JSON.parse(vehicle.features) as string[];
    } catch {
      featuresList = [vehicle.features];
    }
  }

  // Build power string
  let powerStr = "";
  if (vehicle.power) {
    powerStr = vehicle.power + " PS";
    if (vehicle.powerKw) powerStr += "  (" + vehicle.powerKw + " kW)";
  } else if (vehicle.powerKw) {
    powerStr = vehicle.powerKw + " kW";
  }

  const buyerCityLine = [buyer.zip, buyer.city].filter(Boolean).join(" ") +
    (buyer.country ? " / " + buyer.country : "");
  const sellerCityLine = [seller.zip, seller.city].filter(Boolean).join(" ") +
    (seller.country ? " / " + seller.country : "");

  // Vehicle data rows
  const vehicleRows: [string, string][] = [];
  if (vehicle.bodyType) vehicleRows.push(["Aufbau", vehicle.bodyType]);
  if (powerStr) vehicleRows.push(["Leistung", powerStr]);
  if (vehicle.vin) vehicleRows.push(["Fahrgestell-Nr.", vehicle.vin]);
  if (vehicle.hsn) vehicleRows.push(["HSN", vehicle.hsn]);
  if (vehicle.tsn) vehicleRows.push(["TSN", vehicle.tsn]);
  vehicleRows.push(["Fahrzeugbrief-Nr.", vehicle.registrationDocNumber ?? ""]);
  if (vehicle.color) vehicleRows.push(["Farbe", vehicle.color]);
  if (vehicle.transmission) vehicleRows.push(["Getriebe", vehicle.transmission]);
  if (vehicle.displacement) vehicleRows.push(["Hubraum", vehicle.displacement + " ccm"]);
  if (vehicle.fuelType) vehicleRows.push(["Kraftstoff", vehicle.fuelType]);
  const hasTowhitch = featuresList.some(f => /anh.?ng|tow.?hitch|anh.ngevorrichtung/i.test(f));
  vehicleRows.push(["Anh\u00e4ngerkupplung", hasTowhitch ? "ja" : "nein"]);
  if (vehicle.firstRegistration) vehicleRows.push(["Erstzulassung", formatDateDE(vehicle.firstRegistration)]);
  vehicleRows.push(["Km-Stand", vehicle.mileage.toLocaleString("de-DE") + " km"]);
  if (vehicle.huDue) {
    vehicleRows.push(["n\u00e4chste HU", formatMonthYearDE(vehicle.huDue)]);
    vehicleRows.push(["n\u00e4chste AU", formatMonthYearDE(vehicle.huDue)]);
  }
  if (vehicle.previousOwners !== null && vehicle.previousOwners !== undefined) {
    vehicleRows.push(["Anzahl Halter", String(vehicle.previousOwners)]);
  }
  vehicleRows.push(["Taxi-/Miet-/Fahrschule", "nein"]);
  vehicleRows.push(["Unfallfrei (lt. Vorbesitzer)", vehicle.hasDamage ? "nein" : "ja"]);
  vehicleRows.push(["Fahrzeug fahrbereit", "ja"]);
  vehicleRows.push(["Lieferdatum / verbindlich", todayFormatted + " / nein"]);

  const priceFormatted = formatGermanPrice(vehicle.sellingPrice);
  const priceInWords = numberToGermanWords(Math.round(vehicle.sellingPrice));

  const vehicleRowsHtml = vehicleRows
    .map(([label, value]) => `
        <tr>
          <td class="vd-label">${label}</td>
          <td class="vd-value">${value}</td>
        </tr>`)
    .join("");

  const ausstattungHtml = featuresList.length > 0
    ? `<div class="features-block">
        <p class="features-title">Ausstattung</p>
        <p class="features-text">${featuresList.join(" &bull; ")}</p>
      </div>`
    : "";

  const besondereInfoHtml = vehicle.notes
    ? `<div class="features-block">
        <p class="features-title">Besondere Informationen</p>
        <div class="features-text">${vehicle.notes}</div>
      </div>`
    : "";

  const co2Html = vehicle.co2Emission
    ? `<p class="co2-line">Komb. CO2-Emission (gewichtet): ${vehicle.co2Emission} g/km</p>`
    : "";

  const taxNote = vehicle.marginTaxed
    ? `<span class="tax-note">differenzbesteuert</span>`
    : `<span class="tax-note">regelbesteuert* &nbsp;&nbsp; *MwSt. ${vehicle.taxRate}% (=${formatGermanPrice(vehicle.sellingPrice * vehicle.taxRate / 100)})</span>`;

  return `<!DOCTYPE html>
<html lang="de">
<head>
<meta charset="UTF-8">
<title>Verbindliche Bestellung (Vermittlung)</title>
<style>
  * { margin: 0; padding: 0; box-sizing: border-box; }
  body { font-family: Arial, Helvetica, sans-serif; font-size: 9.5pt; color: #000; line-height: 1.45; background: #fff; }
  .page { width: 210mm; min-height: 297mm; padding: 14mm 16mm 14mm 16mm; margin: 0 auto; background: white; }

  .dealer-header { border-bottom: 2px solid #000; padding-bottom: 6px; margin-bottom: 10px; }
  .dealer-brand { display: flex; align-items: flex-start; gap: 12px; }
  .dealer-logo { width: 92px; height: auto; object-fit: contain; flex-shrink: 0; }
  .dealer-name { font-size: 13pt; font-weight: bold; color: #000; }
  .dealer-sub { font-size: 8.5pt; color: #333; margin-top: 2px; }

  .doc-title { font-size: 13pt; font-weight: bold; text-align: center; margin: 10px 0 2px; text-decoration: underline; }
  .doc-subtitle { font-size: 9pt; text-align: center; color: #444; margin-bottom: 4px; }
  .doc-internalref { font-size: 8.5pt; text-align: right; margin-bottom: 8px; }

  .parties { display: flex; gap: 12px; margin-bottom: 10px; }
  .party-block { flex: 1; border: 1px solid #bbb; padding: 7px 9px; font-size: 8.5pt; }
  .party-block-title { font-weight: bold; font-size: 9pt; border-bottom: 1px solid #bbb; margin-bottom: 5px; padding-bottom: 3px; }

  .intro-text { font-size: 8.5pt; margin-bottom: 8px; line-height: 1.5; }

  .vehicle-title { font-size: 12pt; font-weight: bold; margin-bottom: 6px; }

  .vd-table { width: 100%; border-collapse: collapse; margin-bottom: 8px; }
  .vd-table tr { border-bottom: 1px solid #e0e0e0; }
  .vd-label { width: 42%; font-weight: normal; color: #333; padding: 2.5px 4px 2.5px 0; font-size: 9pt; vertical-align: top; }
  .vd-value { width: 58%; padding: 2.5px 4px; font-size: 9pt; font-weight: bold; vertical-align: top; }

  .features-block { margin: 8px 0; }
  .features-title { font-size: 8.5pt; font-weight: bold; margin-bottom: 3px; }
  .features-text { font-size: 8pt; color: #222; line-height: 1.5; }

  .price-row { display: flex; justify-content: space-between; align-items: baseline; margin: 8px 0 4px; }
  .price-line { font-size: 13pt; font-weight: bold; }
  .tax-note { font-size: 8.5pt; color: #333; }
  .price-words { font-size: 9pt; margin-bottom: 2px; }
  .co2-line { font-size: 8.5pt; margin-top: 4px; color: #333; }

  .legal-divider { border-top: 1px solid #bbb; margin: 10px 0 6px; }
  .legal-section-title { font-weight: bold; font-size: 8.5pt; margin-bottom: 5px; }
  .legal-text { font-size: 8pt; line-height: 1.55; color: #222; margin-bottom: 6px; }

  .sig-row { display: flex; gap: 20px; margin-top: 22px; margin-bottom: 6px; }
  .sig-block { flex: 1; }
  .sig-label { font-size: 8pt; color: #555; margin-bottom: 18px; }
  .sig-line { border-top: 1px solid #000; padding-top: 3px; font-size: 8pt; color: #333; }
  .sig-city { font-size: 8.5pt; margin-top: 4px; }

  .doc-footer { border-top: 1.5px solid #000; margin-top: 18px; padding-top: 6px; font-size: 7.5pt; color: #333; text-align: center; line-height: 1.7; }

  @media print {
    body { margin: 0; }
    .page { padding: 12mm 14mm; }
  }
</style>
</head>
<body>
<div class="page">

  ${getDealerHeaderHtml(logoSrc)}

  <div class="doc-title">Verbindliche Bestellung eines gebrauchten Kraftfahrzeuges</div>
  <div class="doc-subtitle">Vermittlungsvertrag</div>
  <div class="doc-internalref">Interne Nr. ${vehicle.vehicleNumber}&nbsp;&nbsp;&nbsp;gewerblich</div>

  <div class="parties">
    <div class="party-block">
      <div class="party-block-title">Vermittler</div>
      <div><strong>${DEALER_NAME}</strong></div>
      <div>${DEALER_ADDRESS}</div>
      <div>${DEALER_CITY}</div>
      <div>Tel. ${DEALER_PHONE}, Web: ${DEALER_WEB}</div>
      <div>Mail: ${DEALER_EMAIL}, USt-IdNr. ${DEALER_TAX_ID}</div>
    </div>
    <div class="party-block">
      <div class="party-block-title">Verk&auml;ufer</div>
      ${seller.company ? `<div><strong>${seller.company}</strong></div>` : ""}
      <div>${seller.firstName} ${seller.lastName}</div>
      ${seller.address ? `<div>${seller.address}</div>` : ""}
      <div>${sellerCityLine}</div>
      ${seller.phone ? `<div>Tel. ${seller.phone}</div>` : ""}
      ${seller.email ? `<div>${seller.email}</div>` : ""}
      ${seller.taxId ? `<div>USt-IdNr.: ${seller.taxId}</div>` : ""}
    </div>
    <div class="party-block">
      <div class="party-block-title">K&auml;ufer</div>
      ${buyer.company ? `<div><strong>${buyer.company}</strong></div>` : ""}
      <div>${buyer.firstName} ${buyer.lastName}</div>
      ${buyer.address ? `<div>${buyer.address}</div>` : ""}
      <div>${buyerCityLine}</div>
      ${buyer.phone ? `<div>Tel. ${buyer.phone}</div>` : ""}
      ${buyer.email ? `<div>${buyer.email}</div>` : ""}
      ${buyer.taxId ? `<div>USt-IdNr.: ${buyer.taxId}</div>` : ""}
    </div>
  </div>

  <p class="intro-text">Der oben genannte K&auml;ufer kauft nach Ma&szlig;gabe und Kenntnisnahme der ausgeh&auml;ndigten Allgemeinen Gesch&auml;ftsbedingungen vom oben genannten Verk&auml;ufer folgendes Fahrzeug:</p>

  <div class="vehicle-title">${vehicle.brand} ${vehicle.model}</div>

  <table class="vd-table">
    <tbody>
      ${vehicleRowsHtml}
    </tbody>
  </table>

  ${ausstattungHtml}
  ${besondereInfoHtml}

  <div class="price-row">
    <div class="price-line">Kaufpreis: ${priceFormatted}</div>
    <div>${taxNote}</div>
  </div>
  <div class="price-words">In Worten: ${priceInWords}</div>

  ${co2Html}

  <div class="legal-divider"></div>

  <div class="legal-section-title">Zahlungsweise + sonstige Vereinbarungen mit Vorrang auf die ausgeh&auml;ndigten Gesch&auml;ftsbedingungen:</div>

  <p class="legal-text">Hiermit bestellt der K&auml;ufer folgendes gebrauchte Kraftfahrzeug unter Ausschluss jeglicher Gew&auml;hrleistung f&uuml;r Sach- und Rechtsm&auml;ngel sofern er nicht eine Garantie f&uuml;r die Beschaffenheit der Sache &uuml;bernommen hat, zu den Umseitigen und, soweit vorhandenen, zu den in der Anlage beigef&uuml;gten, bzw. in einem Verkaufsraum ausliegenden Gesch&auml;ftsbedingungen. Der Ausschluss der Sachm&auml;ngelhaftung gilt nicht bei der Vermittlung eines Verkaufs von einem Unternehmer in Aus&uuml;bung seiner unternehmerischen T&auml;tigkeit an einen Verbraucher. In diesem Fall erfolgt der Verkauf unter Reduzierung der Verj&auml;hrungsfrist f&uuml;r Sach- und Rechtsm&auml;ngel auf ein Jahr.</p>

  <p class="legal-text">Per &Uuml;berweisung auf Konto: DE55673900000058463000 &nbsp;&bull;&nbsp; Fahrzeug bleibt bis zu endg&uuml;ltigen Zahlung Eigentum des Verk&auml;ufers.</p>

  <p class="legal-text">Der Verk&auml;ufer versichert die Richtigkeit der in diesem Vertrag niedergelegten Angaben &uuml;ber das Fahrzeug. Der Lieferzeitpunkt ist, wenn keine anderen Vereinbarungen getroffen wurden, das Datum des Ankaufs. Bei Minderj&auml;hrigen muss der Kaufvertrag durch den gesetzlichen Vertreter unterschrieben werden. Mit seiner Unterschrift best&auml;tigt der Verm&auml;ttler die Annahme der Bestellung.</p>

  <div class="sig-row">
    <div class="sig-block">
      <div class="sig-label">Ort, Datum</div>
      <div class="sig-line">Unterschrift K&auml;ufer</div>
    </div>
    <div class="sig-block">
      <div class="sig-label">&nbsp;</div>
      <div class="sig-line">Unterschrift Vermittler</div>
    </div>
  </div>
  <div class="sig-city">Miltenberg, ${todayFormatted}</div>

  <div class="doc-footer">${getDealerFooterHtml()}</div>

</div>
</body>
</html>`;
}

// POST /api/documents/generate-vermittlung-pdf
documentsRouter.post("/generate-vermittlung-pdf", async (c) => {
  const body = await c.req.json();
  const logoSrc = resolveDocumentLogoSrc(c);
  const { vehicleId, buyerId, buyerType, sellerId, sellerType, manualSeller } = body as {
    vehicleId: string;
    buyerId: string;
    buyerType: "customer" | "supplier";
    sellerId?: string;
    sellerType?: "customer" | "supplier";
    manualSeller?: { firstName: string; lastName: string; company?: string; address?: string; city?: string; zip?: string; country?: string; phone?: string; email?: string; taxId?: string };
  };

  if (!vehicleId || !buyerId) {
    return c.json({ error: { message: "vehicleId and buyerId required", code: "BAD_REQUEST" } }, 400);
  }

  const vehicle = await prisma.vehicle.findUnique({ where: { id: vehicleId } });
  if (!vehicle) return c.json({ error: { message: "Vehicle not found", code: "NOT_FOUND" } }, 404);

  // Resolve buyer
  let buyer: { firstName: string; lastName: string; company: string | null; address: string | null; city: string | null; zip: string | null; country: string | null; email: string | null; phone: string | null; taxId: string | null } | null = null;
  if (buyerType === "customer") {
    const c2 = await prisma.customer.findUnique({ where: { id: buyerId } });
    if (!c2) return c.json({ error: { message: "Buyer (customer) not found", code: "NOT_FOUND" } }, 404);
    buyer = { firstName: c2.firstName, lastName: c2.lastName, company: c2.company, address: c2.address, city: c2.city, zip: c2.zip, country: c2.country, email: c2.email, phone: c2.phone, taxId: c2.taxId };
  } else {
    const s = await prisma.supplier.findUnique({ where: { id: buyerId } });
    if (!s) return c.json({ error: { message: "Buyer (supplier) not found", code: "NOT_FOUND" } }, 404);
    const nameParts = (s.contactPerson ?? s.name).split(" ");
    buyer = {
      firstName: nameParts[0] ?? s.name,
      lastName: nameParts.slice(1).join(" ") || "",
      company: s.supplierType === "gewerblich" ? s.name : null,
      address: s.street ?? s.address ?? null,
      city: s.city ?? null,
      zip: s.zip ?? null,
      country: s.country ?? null,
      email: s.email ?? null,
      phone: s.phone ?? null,
      taxId: null,
    };
  }

  // Resolve seller
  let seller: { firstName: string; lastName: string; company: string | null; address: string | null; city: string | null; zip: string | null; country: string | null; email: string | null; phone: string | null; taxId: string | null } | null = null;
  if (sellerId && sellerType === "customer") {
    const c3 = await prisma.customer.findUnique({ where: { id: sellerId } });
    if (!c3) return c.json({ error: { message: "Seller (customer) not found", code: "NOT_FOUND" } }, 404);
    seller = { firstName: c3.firstName, lastName: c3.lastName, company: c3.company, address: c3.address, city: c3.city, zip: c3.zip, country: c3.country, email: c3.email, phone: c3.phone, taxId: c3.taxId };
  } else if (sellerId && sellerType === "supplier") {
    const s = await prisma.supplier.findUnique({ where: { id: sellerId } });
    if (!s) return c.json({ error: { message: "Seller (supplier) not found", code: "NOT_FOUND" } }, 404);
    const nameParts = (s.contactPerson ?? s.name).split(" ");
    seller = {
      firstName: nameParts[0] ?? s.name,
      lastName: nameParts.slice(1).join(" ") || "",
      company: s.supplierType === "gewerblich" ? s.name : null,
      address: s.street ?? s.address ?? null,
      city: s.city ?? null,
      zip: s.zip ?? null,
      country: s.country ?? null,
      email: s.email ?? null,
      phone: s.phone ?? null,
      taxId: null,
    };
  } else if (manualSeller) {
    seller = { firstName: manualSeller.firstName, lastName: manualSeller.lastName, company: manualSeller.company ?? null, address: manualSeller.address ?? null, city: manualSeller.city ?? null, zip: manualSeller.zip ?? null, country: manualSeller.country ?? null, email: manualSeller.email ?? null, phone: manualSeller.phone ?? null, taxId: manualSeller.taxId ?? null };
  } else {
    return c.json({ error: { message: "Seller info required", code: "BAD_REQUEST" } }, 400);
  }

  const html = generateVermittlungsvertrag(vehicle, buyer, seller, logoSrc);

  try {
    const pdfBuffer = await htmlToPdf(html);
    c.header("Content-Type", "application/pdf");
    c.header("Content-Disposition", `attachment; filename="Vermittlungsvertrag_${vehicle.vehicleNumber}.pdf"`);
    c.header("X-Vehicle-Number", vehicle.vehicleNumber);
    return c.body(pdfBuffer as unknown as ReadableStream);
  } catch (error) {
    console.error("[documents] vermittlung_pdf_generation_failed", {
      vehicleId,
      buyerId,
      buyerType,
      sellerId,
      sellerType,
      error,
    });
    return c.json({ error: { message: "Fehler beim Erstellen des Dokuments", code: "PDF_GENERATION_FAILED" } }, 500);
  }
});

// POST /api/documents/generate-vermittlung-html (for saving)
documentsRouter.post("/generate-vermittlung-html", async (c) => {
  const body = await c.req.json();
  const logoSrc = resolveDocumentLogoSrc(c);
  const { vehicleId, buyerId, buyerType, sellerId, sellerType, manualSeller } = body as {
    vehicleId: string;
    buyerId: string;
    buyerType: "customer" | "supplier";
    sellerId?: string;
    sellerType?: "customer" | "supplier";
    manualSeller?: { firstName: string; lastName: string; company?: string; address?: string; city?: string; zip?: string; country?: string; phone?: string; email?: string; taxId?: string };
  };

  const vehicle = await prisma.vehicle.findUnique({ where: { id: vehicleId } });
  if (!vehicle) return c.json({ error: { message: "Vehicle not found", code: "NOT_FOUND" } }, 404);

  let buyer: { firstName: string; lastName: string; company: string | null; address: string | null; city: string | null; zip: string | null; country: string | null; email: string | null; phone: string | null; taxId: string | null } | null = null;
  if (buyerType === "customer") {
    const c2 = await prisma.customer.findUnique({ where: { id: buyerId } });
    if (!c2) return c.json({ error: { message: "Buyer not found", code: "NOT_FOUND" } }, 404);
    buyer = { firstName: c2.firstName, lastName: c2.lastName, company: c2.company, address: c2.address, city: c2.city, zip: c2.zip, country: c2.country, email: c2.email, phone: c2.phone, taxId: c2.taxId };
  } else {
    const s = await prisma.supplier.findUnique({ where: { id: buyerId } });
    if (!s) return c.json({ error: { message: "Buyer not found", code: "NOT_FOUND" } }, 404);
    const nameParts = (s.contactPerson ?? s.name).split(" ");
    buyer = {
      firstName: nameParts[0] ?? s.name,
      lastName: nameParts.slice(1).join(" ") || "",
      company: s.supplierType === "gewerblich" ? s.name : null,
      address: s.street ?? s.address ?? null,
      city: s.city ?? null,
      zip: s.zip ?? null,
      country: s.country ?? null,
      email: s.email ?? null,
      phone: s.phone ?? null,
      taxId: null,
    };
  }

  let seller: { firstName: string; lastName: string; company: string | null; address: string | null; city: string | null; zip: string | null; country: string | null; email: string | null; phone: string | null; taxId: string | null } | null = null;
  if (sellerId && sellerType === "customer") {
    const c3 = await prisma.customer.findUnique({ where: { id: sellerId } });
    if (!c3) return c.json({ error: { message: "Seller not found", code: "NOT_FOUND" } }, 404);
    seller = { firstName: c3.firstName, lastName: c3.lastName, company: c3.company, address: c3.address, city: c3.city, zip: c3.zip, country: c3.country, email: c3.email, phone: c3.phone, taxId: c3.taxId };
  } else if (sellerId && sellerType === "supplier") {
    const s = await prisma.supplier.findUnique({ where: { id: sellerId } });
    if (!s) return c.json({ error: { message: "Seller not found", code: "NOT_FOUND" } }, 404);
    const nameParts = (s.contactPerson ?? s.name).split(" ");
    seller = {
      firstName: nameParts[0] ?? s.name,
      lastName: nameParts.slice(1).join(" ") || "",
      company: s.supplierType === "gewerblich" ? s.name : null,
      address: s.street ?? s.address ?? null,
      city: s.city ?? null,
      zip: s.zip ?? null,
      country: s.country ?? null,
      email: s.email ?? null,
      phone: s.phone ?? null,
      taxId: null,
    };
  } else if (manualSeller) {
    seller = { firstName: manualSeller.firstName, lastName: manualSeller.lastName, company: manualSeller.company ?? null, address: manualSeller.address ?? null, city: manualSeller.city ?? null, zip: manualSeller.zip ?? null, country: manualSeller.country ?? null, email: manualSeller.email ?? null, phone: manualSeller.phone ?? null, taxId: manualSeller.taxId ?? null };
  } else {
    return c.json({ error: { message: "Seller info required", code: "BAD_REQUEST" } }, 400);
  }

  const html = generateVermittlungsvertrag(vehicle, buyer, seller, logoSrc);
  return c.json({ data: { html, vehicleNumber: vehicle.vehicleNumber } });
});

documentsRouter.post(
  "/generate-handover-protocol-html",
  zValidator("json", HandoverProtocolDocumentGenerateSchema),
  async (c) => {
    const { vehicleId, data } = c.req.valid("json");
    const logoSrc = resolveDocumentLogoSrc(c);
    const sketchSrc = resolveDocumentPublicAssetSrc(c, "car.png");

    const vehicle = await prisma.vehicle.findUnique({ where: { id: vehicleId } });
    if (!vehicle) {
      return c.json({ error: { message: "Vehicle not found", code: "NOT_FOUND" } }, 404);
    }

    const html = generateHandoverProtocolHtml(data, logoSrc, sketchSrc);
    return c.json({ data: { html, vehicleNumber: vehicle.vehicleNumber } });
  }
);

documentsRouter.post(
  "/generate-handover-protocol-pdf",
  zValidator("json", HandoverProtocolDocumentGenerateSchema),
  async (c) => {
    const { vehicleId, data } = c.req.valid("json");
    const logoSrc = resolveDocumentLogoSrc(c);
    const sketchSrc = resolveDocumentPublicAssetSrc(c, "car.png");

    const vehicle = await prisma.vehicle.findUnique({ where: { id: vehicleId } });
    if (!vehicle) {
      return c.json({ error: { message: "Vehicle not found", code: "NOT_FOUND" } }, 404);
    }

    const html = generateHandoverProtocolHtml(data, logoSrc, sketchSrc);

    try {
      const pdfBuffer = await htmlToPdf(html);
      c.header("Content-Type", "application/pdf");
      c.header("Content-Disposition", `attachment; filename="Uebergabeprotokoll_${vehicle.vehicleNumber}.pdf"`);
      c.header("X-Vehicle-Number", vehicle.vehicleNumber);
      return c.body(pdfBuffer as unknown as ReadableStream);
    } catch (error) {
      console.error("[documents] handover_protocol_pdf_generation_failed", { vehicleId, error });
      return c.json({ error: { message: "Fehler beim Erstellen des Dokuments", code: "PDF_GENERATION_FAILED" } }, 500);
    }
  }
);

export { documentsRouter };
